repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
          exclude: '^conda/recipes/.*meta\.yaml$'
        - id: check-added-large-files
    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.10.0.1
      hooks:
        - id: shellcheck
    - repo: https://github.com/PyCQA/isort
      rev: 5.13.2
      hooks:
        - id: isort
    - repo: https://github.com/psf/black
      rev: '24.10.0'
      hooks:
        - id: black
    - repo: https://github.com/PyCQA/flake8
      rev: '7.1.1'
      hooks:
        - id: flake8
    - repo: https://github.com/PyCQA/docformatter
      # commit from https://github.com/PyCQA/docformatter/pull/287
      # TODO: switch to a proper release once that change is released
      rev: '06907d0267368b49b9180eed423fae5697c1e909'
      hooks:
        - id: docformatter
    - repo: https://github.com/pre-commit/mirrors-clang-format
      rev: 'v19.1.2'  # Use the sha / tag you want to point at
      hooks:
        - id: clang-format
          files: \.(cu|cuh|h|cc|inl)$
          types_or: []
    - repo: https://github.com/rapidsai/dependency-file-generator
      rev: v1.16.0
      hooks:
        - id: rapids-dependency-file-generator
          args: ["--clean"]
    - repo: https://github.com/cpplint/cpplint.git
      rev: '2.0.0'
      hooks:
        - id: cpplint
          # match the line length to the one used by clang-format
          # disable whitespace checks as they are already covered by clang-format
          # runtime/references is disabled as this is a more controversial check in the google style guide
          # include_subdir is disabled as it gives false postiives for top level includes
          # readability/nolint is disabled as it interferes with clang-tidy
          args: [
            "--linelength=100",
            "--filter=-whitespace,-runtime/references,-build/include_subdir,-readability/nolint",
          ]

default_language_version:
    python: python3
