repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
            exclude: '^conda/recipes/.*meta\.yaml$'
        -   id: check-added-large-files
    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.10.0.1
      hooks:
        - id: shellcheck
    - repo: https://github.com/PyCQA/isort
      rev: 5.13.2
      hooks:
            - id: isort
    - repo: https://github.com/psf/black
      rev: '24.4.2'
      hooks:
            - id: black
    - repo: https://github.com/PyCQA/flake8
      rev: '7.1.0'
      hooks:
            - id: flake8
    - repo: https://github.com/PyCQA/docformatter
      rev: 'v1.7.5'
      hooks:
            - id: docformatter
    - repo: https://github.com/pre-commit/mirrors-clang-format
      rev: 'v18.1.8'  # Use the sha / tag you want to point at
      hooks:
        - id: clang-format
          files: \.(cu|cuh|h|cc|inl)$
          types_or: []
    - repo: https://github.com/rapidsai/dependency-file-generator
      rev: v1.14.0
      hooks:
        - id: rapids-dependency-file-generator
          args: ["--clean"]
default_language_version:
    python: python3
