c_compiler_version:
  - 11

cxx_compiler_version:
  - 11

c_stdlib:
  - sysroot

c_stdlib_version:
  - "2.17"

cmake_version:
  - ">=3.26.4,!=3.30.0"

cuda_compiler:
  - cuda-nvcc

cuda11_compiler:
  - nvcc

# match the legate / cunumeric pattern of publishing
# CPU-only and GPU-only packages for every variant
gpu_enabled:
  - true
  - false

cupynumeric_version:
  - "=24.11.*"

legate_version:
  - "=24.11.*"
